services:
  llama-server:
    # check images at https://github.com/ggml-org/llama.cpp/blob/master/docs/docker.md
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    ports:
      - "8121:8080"
    volumes:
      - ./translator/models:/models
    gpus: all
    command: >
      --model /models/HY-MT1.5-1.8B-Q4_K_M.gguf  --host 0.0.0.0  --port 8080  --n-gpu-layers 99  --ctx-size 1024

  translator_backend:
    build: .
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "7860:7860"
      - "8052:8052"
    gpus: all
    environment:
      - PYTHONUNBUFFERED=1
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - UV_LINK_MODE=copy
    shm_size: '8gb'
    stdin_open: true
    tty: true
