[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "opencv-python",
    "onnx==1.22.0",
    "protobuf==7.35.1",
    "ml-dtypes==0.5.4",
    "transformers>=5.5.0",
    "simple-lama-inpainting>=0.1.0",
    "accelerate>=1.13.0",
    "fastapi>=0.136.1",
    "uvicorn[standard]>=0.47.0",
    "googletrans>=4.0.2",
    "dbus-next>=0.2.3",
    "pydantic>=2.13.4",
    "huggingface-hub>=1.24.0",
    "python-multipart>=0.0.32",
    "requests>=2.34.2",
]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "SIM", "C4", "TID", "ERA", "RUF", "N"]

fixable = ["E", "F", "I", "UP", "SIM", "C4"]

unfixable = ["B"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint.isort]
combine-as-imports = true
